site_name: Control Your Robot
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.footer
    - navigation.top
    - toc.follow
    - announce.dismiss
    - search.suggest        # 搜索建议
    - search.highlight      # 搜索结果高亮
    - content.tabs          # 在 Markdown 中使用选项卡 (如 ```tabs)
    - content.code.copy     # 为代码块添加复制按钮
    - content.action.edit   # 在页面底部显示编辑链接 (需配置 edit_uri)



plugins:
  - search:
      separator: '[\s\u200b\-]'
  - i18n:
      default_language: en
      languages:
        # - locale: en
        #   name: English
        #   nav:
        #     - Home: index.md
        #     - Getting Started:
        #         - Quickstart: getting_started/quickstart.md
        #         - Installation: getting_started/installation.md
        #     - Usage:
        #         - Features: usage/features.md
        #         - Advanced: usage/advanced.md
        - locale: zh
          name: 中文
          default: true
          nav:
            - 主页: 
              - 主页: index.md
              - 快速开始: getting_started/quickstart_cn.md
              - 安装指南: getting_started/installation_cn.md
            - 用法:
              - 总览: usage/start.md
              - controller: 
                - 基础控制器类(controller): usage/controller/controller_cn.md
                - 机械臂控制器类(arm_controller): usage/controller/arm_controller_cn.md
                - 底盘控制器类(mobile_controller): usage/controller/mobile_controller_cn.md
                - 灵巧手控制器类(dexhand_controller): usage/controller/dexhand_controller_cn.md
              - sensor: 
                - 传感器类(sensor): usage/sensor/sensor_cn.md
                - 视觉传感器类(vision_sensor): usage/sensor/vision_sensor_cn.md
                - 触觉传感器类(touch_sensor): usage/sensor/touch_sensor_cn.md
                - 遥操传感器类(teleop_sensor): usage/sensor/teleoperation_sensor_cn.md
              - policy:
                - 策略部署: usage/policy/model_cn.md
              - scipts:
                - 服务器&客户端操作(clinet&server): usage/scripts/client_server_cn.md
              - my_robot:
                - 机器人基类(base_robot): usage/my_robot/base_robot_cn.md
                - 自定义机器人: usage/my_robot/robot_cn.md
                - 机器人遥操: usage/my_robot/teleop_robot_cn.md
              - example:
                - 数据采集(collect): usage/example/collect_cn.md
                - 模型部署(deploy): usage/example/deploy_cn.md
              - utils:
                - 数据处理(data_handler): usage/utils/data_handler_cn.md
                - 时间同步器(time_scheduler): usage/utils/time_scheduler_cn.md
                - 双向套接字通讯(biosocket): usage/utils/biosocket_cn.md
                - 组件式多进程单元(component_worker): usage/utils/component_worker_cn.md
                - 机器人式多进程单元(robot_worker): usage/utils/robot_worker_cn.md
                - ROS1发布(ros_publisher): usage/utils/ros_publisher_cn.md
                - ROS1订阅(ros_subscriber): usage/utils/ros_subscriber_cn.md
                - ROS2发布(ros2_publisher): usage/utils/ros2_publisher_cn.md
                - ROS2订阅(ros2_subscriber): usage/utils/ros2_subscriber_cn.md
            - 展示:
              - 采集展示: demo/collect_demo_cn.md