site_name: Control Your Robot
theme:
  name: material
  language: en

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        # - locale: en
        #   name: English
        #   nav:
        #     - Home: index.md
        #     - Getting Started:
        #         - Quickstart: getting_started/quickstart.md
        #         - Installation: getting_started/installation.md
        #     - Usage:
        #         - Features: usage/features.md
        #         - Advanced: usage/advanced.md
        - locale: zh
          name: 中文
          default: true
          nav:
            - 主页: index.md  # ⚠️ 不要加 zh/ 前缀
            - 入门:
                - 快速开始: getting_started/quickstart_cn.md
                - 安装指南: getting_started/installation_cn.md
            - 用法:
                - controller: 
                  - 基础控制器类: usage/controller/controller_cn.md
                  - 机械臂控制器类: usage/controller/arm_controller_cn.md
                  - 底盘控制器类: usage/controller/mobile_controller_cn.md
                  - 灵巧手控制器类: usage/controller/dexhand_controller_cn.md
                - sensor: 
                  - 传感器类: usage/sensor/sensor_cn.md
                  - 视觉传感器类: usage/sensor/vision_sensor_cn.md
                  - 触觉传感器类: usage/sensor/touch_sensor_cn.md
                  - 遥操传感器类: usage/sensor/teleoperation_sensor_cn.md
                - my_robot:
                  - 自定义机器人: usage/my_robot/robot_cn.md
                - collect:
                  - 数据采集: usage/example/collect_cn.md
                  - 模型部署: usage/example/deploy_cn.md
                - utils:
                  - 时间同步器: usage/utils/time_scheduler_cn.md

